CREATE TABLE CUPID.TB_BOARD
(
    IDX INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    PARENT_IDX INT,
    TITLE VARCHAR(100) NOT NULL,
    CONTENTS VARCHAR(4000) NOT NULL,
    HIT_CNT INT NOT NULL,
    DEL_GB VARCHAR(1) DEFAULT 'N' NOT NULL,
    CREA_DTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREA_ID VARCHAR(30) NOT NULL
);
  

CREATE TABLE CUPID.TB_FILE
(
  IDX   INT auto_increment,
  BOARD_IDX INT NOT NULL,
  ORIGINAL_FILE_NAME VARCHAR(260) NOT NULL,
  STORED_FILE_NAME VARCHAR(50) NOT NULL,
  FILE_SIZE INT,
  CREA_DTM  DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CREA_ID   VARCHAR(30) NOT NULL,
  DEL_GB    VARCHAR(1) DEFAULT 'N' NOT NULL,
  PRIMARY KEY (IDX)
);



CREATE TABLE TB_MEMO
(
    IDX INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    CONTENTS VARCHAR(4000) NOT NULL,
    DEL_GB VARCHAR(1) DEFAULT 'N' NOT NULL,
    CREA_DTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREA_ID VARCHAR(30) NOT NULL
)
;


CREATE TABLE tb_menu (
  MENU_ID varchar(15) NOT NULL,
  MENU_NAME varchar(50) DEFAULT NULL,
  PROGRAM_ID varchar(15) DEFAULT NULL,
  MENU_LEVEL int(11) DEFAULT NULL,
  UP_MENU_ID varchar(15) DEFAULT NULL,
  NOTES varchar(200) DEFAULT NULL,
  URL varchar(200) DEFAULT NULL,
  SORT_KEY int(11) DEFAULT NULL,
  USE_YN char(1) DEFAULT NULL,
  MENU_TYPE char(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE PROCEDURE SP_BOARD_INSERT ()
BEGIN

	DECLARE val INT DEFAULT 0;
    
    WHILE val < 500 DO
    
            INSERT INTO TB_BOARD
			(
				TITLE, 
			    CONTENTS, 
			    HIT_CNT, 
			    DEL_GB, 
			    CREA_DTM, 
			    CREA_ID
			)
			VALUES
			(
				CONCAT('제목 ', val), 
			    CONCAT('내용 ', val),
			    0, 
			    'N', 
			    NOW(), 
			    'Admin'
			);
            
	    SET val = val + 1;
	END WHILE;

END

